### PR TITLE
Add :style/indent meta to macros with body parameters.

### PR DESCRIPTION
**Pull request by ReilySiegel**
This metadata is used by CIDER, clojure-lsp, and possibly other editors to support proper indentation of macros.

### CODE REVIEW

**Comment by dustingetz** [comment]
Thanks @ReilySiegel for the PR, can you provide more background info about what problem this solves and links to documentation so i can see if I agree with your decisions?

**Comment by ReilySiegel** [comment]
This enables certain editors, as mentioned above, to pull this metadata from the macro vars and use the information contained to determine indentation. CIDER's documentation for this feature is [here](https://docs.cider.mx/cider/indent_spec.html). The definitions I used correspond to the [Clojure Style Guide](https://guide.clojure.style), as other schemes of indentation such as Tonsky indentation do not require runtime information, and thus don't use this metadata.

**Comment by dustingetz** [comment]
Sorry I got busy – can you send me a screenshot demonstrating the format you've encoded?

**Comment by ReilySiegel** [comment]
Here is how cider would indent various Electric macros by default:
```clojure
(local
 (some)
 (body)
 (forms))

(local (some)
       (body)
       (forms))

(for [x xs]
     (some)
     (body)
     (forms))

(for
 [x xs]
 (some)
 (body)
 (forms))

(for-by identity [x xs]
        (some)
        (body)
        (forms))

(for-by
 identity [x xs]
 (some)
 (body)
 (forms))

(for-by
 identity
 [x xs]
 (some)
 (body)
 (forms))
```
And here is how they would be indented with the `:style/indent` metadata:
```clojure
;; {:style/indent 0}
(local
  (some)
  (body)
  (forms))

(local (some)
       (body)
       (forms))

;; {:style/indent 1}
(for [x xs]
  (some)
  (body)
  (forms))

(for
    [x xs]
  (some)
  (body)
  (forms))

;; {:style/indent 2}
(for-by identity [x xs]
  (some)
  (body)
  (forms))

(for-by
    identity [x xs]
  (some)
  (body)
  (forms))

(for-by
    identity
    [x xs]
  (some)
  (body)
  (forms))
```

**Comment by dustingetz** [comment]
Signed CA received, thanks @ReilySiegel

**Pull request merged**
